"""Typed exception hierarchy for the RyotenkAI monorepo.

Single root: :class:`RyotenkAIError`. Two abstract markers:
:class:`DomainError` (4xx semantics) and :class:`InfrastructureError`
(5xx semantics). Plus :class:`InternalError` catch-all and
:class:`TransportError` for Mac-side synthesised tunnel failures.

Every concrete subclass pins ``code: ClassVar[ErrorCode]`` and
``status: ClassVar[int]`` so the boundary protocol (RFC 9457
problem+json) can be produced via :meth:`RyotenkAIError.as_problem`
without ad-hoc construction at raise sites.

See ``docs/plans/sharded-stargazing-wigderson.md`` for the design.
"""

from ryotenkai_shared.errors.base import (
    DomainError,
    InfrastructureError,
    InternalError,
    RyotenkAIError,
    TransportError,
)
from ryotenkai_shared.errors.domain import (
    AttemptInvalidError,
    AttemptNotFoundError,
    ClientDisconnectError,
    ConfigDriftError,
    ConfigFileNotFoundError,
    ConfigInvalidError,
    DatasetLoadFailedError,
    DatasetNotFoundError,
    DatasetValidationFailedError,
    DiagnosticInvalidIncludeError,
    EngineConfigInvalidError,
    EngineNotRegisteredError,
    FileTargetInvalidError,
    FileTooLargeError,
    HFAuthFailedError,
    HFNotFoundError,
    ImportCheckInvalidModuleNameError,
    ImportCheckTooManyModulesError,
    IntegrationNotFoundError,
    IntegrationTypeInvalidError,
    JobInProgressError,
    JobNotFoundError,
    JobSpecInvalidError,
    JobStateInvalidError,
    JobSubmissionMissingError,
    LaunchInProgressError,
    LogFileRangeInvalidError,
    LogNameInvalidError,
    LogNotAvailableError,
    LogOffsetOutOfRangeError,
    LoopbackRequiredError,
    NoActiveJobError,
    NoAttemptsError,
    PermissionDeniedError,
    PluginNotFoundError,
    PluginUnpackFailedError,
    PresetNotFoundError,
    ProjectAlreadyExistsError,
    ProjectDirectoryMissingError,
    ProjectNotFoundError,
    ProviderAuthFailedError,
    ProviderNotFoundError,
    ProviderTokenInvalidError,
    RunIsActiveError,
    RunNotFoundError,
    StateLoadFailedError,
    StateLockedError,
    StopNotAllowedError,
    StrategyChainInvalidError,
)
from ryotenkai_shared.errors.infra import (
    DatasetsLibraryMissingError,
    FileWriteFailedError,
    HFLoadFailedError,
    InferenceUnavailableError,
    LaunchPreparationError,
    MetricsBufferTooLargeError,
    ModelLoadFailedError,
    PipelineStageFailedError,
    ProviderRateLimitedError,
    ProviderUnavailableError,
    ReportGenerationFailedError,
    ResourcesUnavailableError,
    RunnerBusyError,
    RunnerNotReadyError,
    RunnerUnreachableError,
    SSHConnectionFailedError,
    SSHExecFailedError,
    SSHTransferFailedError,
    SpawnFailedError,
    TrainingFailedError,
    TrainingOOMError,
    TrainingTimeoutError,
    WorkspaceStoreFailedError,
)

__all__ = [
    # base
    "RyotenkAIError",
    "DomainError",
    "InfrastructureError",
    "InternalError",
    "TransportError",
    # domain (4xx)
    "AttemptInvalidError",
    "AttemptNotFoundError",
    "ClientDisconnectError",
    "ConfigInvalidError",
    "ConfigDriftError",
    "ConfigFileNotFoundError",
    "DatasetLoadFailedError",
    "DatasetNotFoundError",
    "DatasetValidationFailedError",
    "DiagnosticInvalidIncludeError",
    "EngineConfigInvalidError",
    "EngineNotRegisteredError",
    "FileTargetInvalidError",
    "FileTooLargeError",
    "HFAuthFailedError",
    "HFNotFoundError",
    "ImportCheckInvalidModuleNameError",
    "ImportCheckTooManyModulesError",
    "IntegrationNotFoundError",
    "IntegrationTypeInvalidError",
    "JobInProgressError",
    "JobNotFoundError",
    "JobSpecInvalidError",
    "JobStateInvalidError",
    "JobSubmissionMissingError",
    "LaunchInProgressError",
    "LogFileRangeInvalidError",
    "LogNameInvalidError",
    "LogNotAvailableError",
    "LogOffsetOutOfRangeError",
    "LoopbackRequiredError",
    "NoActiveJobError",
    "NoAttemptsError",
    "PermissionDeniedError",
    "PluginNotFoundError",
    "PluginUnpackFailedError",
    "PresetNotFoundError",
    "ProjectAlreadyExistsError",
    "ProjectDirectoryMissingError",
    "ProjectNotFoundError",
    "ProviderAuthFailedError",
    "ProviderNotFoundError",
    "ProviderTokenInvalidError",
    "RunIsActiveError",
    "RunNotFoundError",
    "StateLoadFailedError",
    "StateLockedError",
    "StopNotAllowedError",
    "StrategyChainInvalidError",
    # infra (5xx)
    "DatasetsLibraryMissingError",
    "FileWriteFailedError",
    "HFLoadFailedError",
    "InferenceUnavailableError",
    "LaunchPreparationError",
    "MetricsBufferTooLargeError",
    "ModelLoadFailedError",
    "PipelineStageFailedError",
    "ProviderRateLimitedError",
    "ProviderUnavailableError",
    "ReportGenerationFailedError",
    "ResourcesUnavailableError",
    "RunnerBusyError",
    "RunnerNotReadyError",
    "RunnerUnreachableError",
    "SSHConnectionFailedError",
    "SSHExecFailedError",
    "SSHTransferFailedError",
    "SpawnFailedError",
    "TrainingFailedError",
    "TrainingOOMError",
    "TrainingTimeoutError",
    "WorkspaceStoreFailedError",
]
