#!/usr/bin/env python3
"""Project ``provider.toml`` manifests into pod-side sub-manifests.

The pod runtime cannot import :mod:`ryotenkai_providers` directly
(sentinel test ``test_pod_does_not_import_control_or_providers``
forbids it). Instead, this script reads each provider's full manifest
and writes a minimal pod-only projection to
``packages/pod/src/ryotenkai_pod/runner/runtime/pod_manifests/<id>.toml``.

The pod-side registry parses these projected files with stdlib
``tomllib`` at lifespan boot — no Pydantic, no shared schema package
beyond what's already in ``ryotenkai_shared``.

Projection contents (the **only** fields the pod needs):
* ``schema_version`` — for forward-compat rejection.
* ``[provider]`` ``id``.
* ``[capabilities]`` ``supports_lifecycle_actions`` — gate flag for
  the pod's lifespan to decide whether to even resolve a lifecycle
  client class.
* ``[entry_points.pod_lifecycle_client]`` — only present when
  ``supports_lifecycle_actions=true`` (the manifest schema enforces
  this in the Mac-side ``ProviderManifest`` validator; this script
  inherits the same invariant).

What's intentionally absent on the pod side:
* Mac-only entry points (training / inference / config_schema /
  resume_factory).
* Mac-only cap flags (``is_local`` / ``supports_log_download`` /
  ``volume_kind`` / ``runner_workspace_root`` — the runner reads its
  own runtime-env vars for these).
* ``required_env`` — pre-factory secret resolution is a Mac-side
  concern; the pod gets its env directly from the launcher.

Usage::

    python packages/providers/scripts/compile_pod_manifests.py
    # or via Makefile target:
    # make compile-pod-manifests

CI step ``make check-pod-manifests`` re-runs this script and asserts
``git diff --exit-code`` on the projection target — drift between
``provider.toml`` and the shipped pod sub-manifest fails the build.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def _workspace_root() -> Path:
    """Walk up to the uv workspace root.

    Mirrors the helper in ``ryotenkai_shared.config.runtime`` — same
    invariant: workspace = nearest ancestor with both ``pyproject.toml``
    and ``packages/``. Kept inline because this script may be run from
    arbitrary CWDs (CI, pre-commit, devs invoking it from the repo root
    or from inside a worktree).
    """
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "pyproject.toml").is_file() and (parent / "packages").is_dir():
            return parent
    return Path.cwd()


_REPO_ROOT = _workspace_root()
_PROVIDERS_ROOT = _REPO_ROOT / "packages" / "providers" / "src" / "ryotenkai_providers"
_POD_MANIFESTS_DIR = (
    _REPO_ROOT
    / "packages"
    / "pod"
    / "src"
    / "ryotenkai_pod"
    / "runner"
    / "runtime"
    / "pod_manifests"
)


# ---------------------------------------------------------------------------
# Projection
# ---------------------------------------------------------------------------


def project_to_pod_manifest(provider_manifest: dict[str, Any]) -> dict[str, Any]:
    """Pure function: full provider.toml dict → pod sub-manifest dict.

    Idempotent — round-tripping through TOML and re-parsing yields the
    same dict. Tested in ``packages/providers/tests/...`` (drift test).
    """
    caps_in = provider_manifest.get("capabilities", {})
    ep_in = provider_manifest.get("entry_points", {})

    out: dict[str, Any] = {
        "schema_version": provider_manifest.get("schema_version", 1),
        "provider": {"id": provider_manifest["provider"]["id"]},
        "capabilities": {
            "supports_lifecycle_actions": bool(
                caps_in.get("supports_lifecycle_actions", False)
            ),
        },
    }
    pod_lc = ep_in.get("pod_lifecycle_client")
    if pod_lc is not None:
        out["entry_points"] = {
            "pod_lifecycle_client": {
                "module": pod_lc["module"],
                "class": pod_lc["class"],
            }
        }
    return out


def render_pod_manifest_toml(projection: dict[str, Any]) -> str:
    """Hand-rendered TOML — keeps output deterministic + readable.

    Stdlib ``tomllib`` is read-only; ``tomli_w`` is a third-party dep
    we don't need just to emit two scalar tables. Render explicitly
    with stable key order so the file diffs cleanly.
    """
    pid = projection["provider"]["id"]
    caps = projection["capabilities"]
    lines = [
        "# AUTO-GENERATED by packages/providers/scripts/compile_pod_manifests.py.",
        "# DO NOT EDIT BY HAND — regenerate from the source ``provider.toml``.",
        "# CI step ``make check-pod-manifests`` fails if this file drifts.",
        "",
        f"schema_version = {projection['schema_version']}",
        "",
        "[provider]",
        f'id = "{pid}"',
        "",
        "[capabilities]",
        f"supports_lifecycle_actions = {str(caps['supports_lifecycle_actions']).lower()}",
        "",
    ]
    ep = projection.get("entry_points", {}).get("pod_lifecycle_client")
    if ep is not None:
        lines += [
            "[entry_points.pod_lifecycle_client]",
            f'module = "{ep["module"]}"',
            f'class  = "{ep["class"]}"',
            "",
        ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def discover_provider_manifests(root: Path) -> list[Path]:
    """Walk ``packages/providers/.../<id>/provider.toml`` files."""
    if not root.is_dir():
        return []
    found: list[Path] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if child.name.startswith(".") or child.name in {
            "training",
            "inference",
            "scripts",
            "tests",
            "__pycache__",
        }:
            continue
        candidate = child / "provider.toml"
        if candidate.is_file():
            found.append(candidate)
    return found


def compile_pod_manifests(
    *,
    providers_root: Path = _PROVIDERS_ROOT,
    pod_manifests_dir: Path = _POD_MANIFESTS_DIR,
    check: bool = False,
    verbose: bool = False,
) -> int:
    """Project every provider manifest. Return 0 on success, non-zero on
    diff (when ``check=True``) or write failure."""
    pod_manifests_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}
    for src in discover_provider_manifests(providers_root):
        with src.open("rb") as fh:
            data = tomllib.load(fh)
        projection = project_to_pod_manifest(data)
        rendered = render_pod_manifest_toml(projection)
        pid = projection["provider"]["id"]
        target = pod_manifests_dir / f"{pid}.toml"
        written[pid] = rendered
        existing = target.read_text(encoding="utf-8") if target.is_file() else ""
        if existing == rendered:
            if verbose:
                print(f"  unchanged: {pid}")
            continue
        if check:
            print(
                f"DRIFT: pod sub-manifest {target.relative_to(_REPO_ROOT)} "
                f"is stale. Re-run ``python {Path(__file__).relative_to(_REPO_ROOT)}`` "
                f"and commit.",
                file=sys.stderr,
            )
            return 1
        target.write_text(rendered, encoding="utf-8")
        print(f"  wrote: {target.relative_to(_REPO_ROOT)}")
    # Drop stale projections (provider deleted, manifest renamed) so the
    # pod-side registry can't pick up a phantom from a previous run.
    valid_names = {f"{pid}.toml" for pid in written}
    for stale in pod_manifests_dir.glob("*.toml"):
        if stale.name not in valid_names:
            if check:
                print(
                    f"DRIFT: stale pod sub-manifest "
                    f"{stale.relative_to(_REPO_ROOT)} has no source provider.toml.",
                    file=sys.stderr,
                )
                return 1
            stale.unlink()
            print(f"  removed: {stale.relative_to(_REPO_ROOT)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write; exit 1 if any output would change. CI mode.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Print unchanged files too.",
    )
    args = parser.parse_args(argv)
    return compile_pod_manifests(check=args.check, verbose=args.verbose)


if __name__ == "__main__":
    raise SystemExit(main())
