#!/usr/bin/env python3
"""Export per-provider config Pydantic schemas as JSON Schema files.

For each provider, takes the Pydantic model declared in
``[entry_points.config_schema]`` of its ``provider.toml``, calls
:meth:`pydantic.BaseModel.model_json_schema`, and writes the result to
``packages/providers/src/ryotenkai_providers/<id>/config_schema.generated.json``.

Why:
* The Web UI's ConfigBuilder (``web/src/components/ConfigBuilder/``)
  renders a form per provider. Today the field set is duplicated
  between the Pydantic model and a hand-maintained TypeScript shape —
  the two drift quietly. Generating JSON Schema from the Pydantic side
  gives the frontend a single source of truth: it either imports the
  generated ``.json`` directly, or fetches it from
  ``GET /api/providers/<id>/config-schema`` (backend reads the same
  file or calls ``registry.get_config_json_schema(id)``).
* Generation is **one-way** (Pydantic → JSON Schema). Editing the JSON
  by hand is futile; the script overwrites it. We mark the file with
  an ``$comment`` so reviewers can spot the auto-generated header.
* The ``--check`` flag lets CI assert idempotence — running this
  script and ``git diff --exit-code`` rejects PRs that updated the
  Pydantic model without regenerating the JSON.

Usage::

    python packages/providers/scripts/generate_config_json_schemas.py
    python packages/providers/scripts/generate_config_json_schemas.py --check

Generated files are versioned in git so frontends without backend
access (storybook fixtures, schema explorer demos) can read them
directly off the repo. The ``$comment`` header explains how to
regenerate them.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path


def _workspace_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "pyproject.toml").is_file() and (parent / "packages").is_dir():
            return parent
    return Path.cwd()


_REPO_ROOT = _workspace_root()
_PROVIDERS_ROOT = _REPO_ROOT / "packages" / "providers" / "src" / "ryotenkai_providers"

#: Header comment baked into every generated JSON Schema. Operators /
#: reviewers spotting this know not to edit the file by hand.
_GENERATED_COMMENT = (
    "AUTO-GENERATED by packages/providers/scripts/generate_config_json_schemas.py "
    "from the Pydantic model declared in entry_points.config_schema of provider.toml. "
    "Do not edit by hand."
)


def _discover_manifests(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    out: list[Path] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if child.name in {"training", "inference", "scripts", "tests", "__pycache__"}:
            continue
        if child.name.startswith("."):
            continue
        m = child / "provider.toml"
        if m.is_file():
            out.append(m)
    return out


def _generate_one(manifest_path: Path) -> tuple[str, str]:
    """Resolve the config schema class + render its JSON Schema.

    Returns ``(provider_id, json_text)``. Json output is pretty-printed
    with 2-space indent and a trailing newline so diffs stay readable.
    """
    with manifest_path.open("rb") as fh:
        raw = tomllib.load(fh)
    provider_id = raw["provider"]["id"]
    cs = raw["entry_points"]["config_schema"]
    import importlib

    module = importlib.import_module(cs["module"])
    cls = getattr(module, cs["class"])
    schema = cls.model_json_schema()
    # Wrap with a comment header so reviewers can spot the file as
    # auto-generated. ``$comment`` is the JSON Schema-canonical key for
    # author/tooling annotations.
    schema = {"$comment": _GENERATED_COMMENT, **schema}
    return provider_id, json.dumps(schema, indent=2, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write; exit 1 if any output would change. CI mode.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Print unchanged files too.",
    )
    args = parser.parse_args(argv)

    manifests = _discover_manifests(_PROVIDERS_ROOT)
    if not manifests:
        print(f"No provider.toml files under {_PROVIDERS_ROOT}", file=sys.stderr)
        return 1

    drifted = False
    for m in manifests:
        try:
            provider_id, generated = _generate_one(m)
        except Exception as exc:
            print(
                f"❌ {m.parent.name}: failed to generate JSON Schema: {exc}",
                file=sys.stderr,
            )
            return 1
        target = m.parent / "config_schema.generated.json"
        existing = target.read_text(encoding="utf-8") if target.is_file() else ""
        if existing == generated:
            if args.verbose:
                print(f"  unchanged: {target.relative_to(_REPO_ROOT)}")
            continue
        if args.check:
            print(
                f"DRIFT: {target.relative_to(_REPO_ROOT)} is stale. "
                f"Re-run ``python {Path(__file__).relative_to(_REPO_ROOT)}`` "
                f"and commit.",
                file=sys.stderr,
            )
            drifted = True
            continue
        target.write_text(generated, encoding="utf-8")
        print(f"  wrote: {target.relative_to(_REPO_ROOT)}")
    return 1 if drifted else 0


if __name__ == "__main__":
    raise SystemExit(main())
