/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["config-validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default */
        get: operations["config-default"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schema
         * @description Return the full PipelineConfig JSON schema for the UI builder.
         */
        get: operations["config-schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Presets
         * @description Return curated starter configs from ``community/presets/``.
         *
         *     Each preset lives in its own folder with a ``manifest.toml`` (id,
         *     display name, description, size tier, optional v2 scope/requirements/
         *     placeholders) and the actual config YAML referenced via
         *     ``[preset.entry_point]``.
         */
        get: operations["config-presets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/presets/{preset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Preset
         * @description Dry-run: apply ``preset_id`` to ``current_config`` and return the
         *     resulting config plus a structured diff, requirements check, and
         *     placeholder hints.
         *
         *     The endpoint never writes anything — it's what the frontend calls to
         *     populate the Apply-preset modal (three sections: what changes / what's
         *     preserved / what the user still needs to fill).
         */
        post: operations["config-preview_preset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/attempts/{attempt_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attempt */
        get: operations["attempts-get_attempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/attempts/{attempt_no}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stages */
        get: operations["attempts-get_stages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/attempts/{attempt_no}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Chunk */
        get: operations["logs-get_log_chunk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/attempts/{attempt_no}/logs/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["logs-list_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/restart-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restart Points */
        get: operations["launch-restart_points"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/default-launch-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Launch Mode */
        get: operations["launch-default_launch_mode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch */
        post: operations["launch-launch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrupt */
        post: operations["launch-interrupt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/reports/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Defaults */
        get: operations["plugins-get_report_defaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plugins */
        get: operations["plugins-list_plugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["projects-list_projects"];
        put?: never;
        /** Create Project */
        post: operations["projects-create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["projects-get_project"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Unregister a project. By default also removes the on-disk
         *     workspace — pass ``?delete_files=false`` to keep the directory.
         */
        delete: operations["projects-delete_project"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Description */
        put: operations["projects-update_description"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["projects-get_config"];
        /** Save Config */
        put: operations["projects-save_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Env */
        get: operations["projects-get_project_env"];
        /** Save Project Env */
        put: operations["projects-save_project_env"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Config */
        post: operations["projects-validate_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/config/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["projects-list_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/config/versions/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Version */
        get: operations["projects-read_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/config/versions/{filename}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Version */
        post: operations["projects-restore_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/config/versions/{filename}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Toggle Favorite */
        put: operations["projects-toggle_favorite"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Types */
        get: operations["providers-list_types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["providers-list_providers"];
        put?: never;
        /** Create Provider */
        post: operations["providers-create_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider */
        get: operations["providers-get_provider"];
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["providers-delete_provider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["providers-get_config"];
        /** Save Config */
        put: operations["providers-save_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Config */
        post: operations["providers-validate_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/config/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["providers-list_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/config/versions/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Version */
        get: operations["providers-read_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/config/versions/{filename}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Version */
        post: operations["providers-restore_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["reports-get_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["runs-list_runs"];
        put?: never;
        /** Create Run */
        post: operations["runs-create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["runs-get_run"];
        put?: never;
        post?: never;
        /** Delete Run */
        delete: operations["runs-delete_run"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttemptDetail */
        AttemptDetail: {
            /** Attempt Id */
            attempt_id: string;
            /** Attempt No */
            attempt_no: number;
            /** Runtime Name */
            runtime_name: string;
            /** Requested Action */
            requested_action: string;
            /** Effective Action */
            effective_action: string;
            /** Restart From Stage */
            restart_from_stage?: string | null;
            /** Status */
            status: string;
            /** Status Icon */
            status_icon?: string | null;
            /** Status Color */
            status_color?: string | null;
            /** Started At */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Training Critical Config Hash
             * @default
             */
            training_critical_config_hash: string;
            /**
             * Late Stage Config Hash
             * @default
             */
            late_stage_config_hash: string;
            /**
             * Model Dataset Config Hash
             * @default
             */
            model_dataset_config_hash: string;
            /** Root Mlflow Run Id */
            root_mlflow_run_id?: string | null;
            /** Pipeline Attempt Mlflow Run Id */
            pipeline_attempt_mlflow_run_id?: string | null;
            /** Training Run Id */
            training_run_id?: string | null;
            /** Enabled Stage Names */
            enabled_stage_names?: string[];
            /** Stage Runs */
            stage_runs?: {
                [key: string]: components["schemas"]["StageRun"];
            };
            /** Duration Seconds */
            duration_seconds?: number | null;
        };
        /** ConfigCheck */
        ConfigCheck: {
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "fail";
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ConfigPreset */
        ConfigPreset: {
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Yaml */
            yaml: string;
            /**
             * Size Tier
             * @default
             */
            size_tier: string;
            scope?: components["schemas"]["PresetScopeOut"] | null;
            requirements?: components["schemas"]["PresetRequirementsOut"] | null;
            /** Placeholders */
            placeholders?: {
                [key: string]: string;
            };
        };
        /** ConfigPresetsResponse */
        ConfigPresetsResponse: {
            /** Presets */
            presets?: components["schemas"]["ConfigPreset"][];
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Yaml */
            yaml: string;
            /** Parsed Json */
            parsed_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** ConfigTemplate */
        ConfigTemplate: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** ConfigValidateRequest */
        ConfigValidateRequest: {
            /** Config Path */
            config_path: string;
        };
        /** ConfigValidationResult */
        ConfigValidationResult: {
            /** Ok */
            ok: boolean;
            /** Config Path */
            config_path: string;
            /** Checks */
            checks?: components["schemas"]["ConfigCheck"][];
            /** Field Errors */
            field_errors?: {
                [key: string]: string[];
            };
        };
        /** ConfigVersion */
        ConfigVersion: {
            /** Filename */
            filename: string;
            /** Created At */
            created_at: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
        };
        /** ConfigVersionDetail */
        ConfigVersionDetail: {
            /** Filename */
            filename: string;
            /** Yaml */
            yaml: string;
        };
        /** ConfigVersionsResponse */
        ConfigVersionsResponse: {
            /** Versions */
            versions: components["schemas"]["ConfigVersion"][];
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
            /**
             * Id
             * @description Slug used on disk. Derived from name when omitted.
             */
            id?: string | null;
            /**
             * Path
             * @description Absolute path; when omitted the project lives under ~/.ryotenkai/projects/<id>/.
             */
            path?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** CreateProviderRequest */
        CreateProviderRequest: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Id
             * @description Slug used on disk. Derived from name when omitted.
             */
            id?: string | null;
            /**
             * Path
             * @description Absolute path; when omitted the provider lives under ~/.ryotenkai/providers/<id>/.
             */
            path?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Run Id
             * @description Explicit run id; auto-suggested when omitted
             */
            run_id?: string | null;
            /**
             * Subgroup
             * @description Optional subgroup relative to runs_dir
             */
            subgroup?: string | null;
        };
        /** DefaultConfigResponse */
        DefaultConfigResponse: {
            /** Runs Dir */
            runs_dir: string;
            /** Config Templates */
            config_templates?: components["schemas"]["ConfigTemplate"][];
        };
        /** DeleteIssueSchema */
        DeleteIssueSchema: {
            /** Run Dir */
            run_dir: string;
            /** Phase */
            phase: string;
            /** Message */
            message: string;
        };
        /** DeleteResultSchema */
        DeleteResultSchema: {
            /** Target */
            target: string;
            /** Run Dirs */
            run_dirs?: string[];
            /** Deleted Mlflow Run Ids */
            deleted_mlflow_run_ids?: string[];
            /** Local Deleted */
            local_deleted: boolean;
            /** Issues */
            issues?: components["schemas"]["DeleteIssueSchema"][];
            /** Is Success */
            is_success: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Runs Dir */
            runs_dir: string;
            /** Runs Dir Readable */
            runs_dir_readable: boolean;
            /**
             * Version
             * @default v0.1.0
             */
            version: string;
        };
        /** InterruptResponse */
        InterruptResponse: {
            /** Interrupted */
            interrupted: boolean;
            /** Pid */
            pid?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /** LaunchRequestSchema */
        LaunchRequestSchema: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "new_run" | "fresh" | "resume" | "restart";
            /** Config Path */
            config_path?: string | null;
            /** Restart From Stage */
            restart_from_stage?: string | null;
            /**
             * Log Level
             * @default INFO
             * @enum {string}
             */
            log_level: "INFO" | "DEBUG";
        };
        /** LaunchResponse */
        LaunchResponse: {
            /** Pid */
            pid: number;
            /** Launched At */
            launched_at: string;
            /** Command */
            command: string[];
            /** Launcher Log */
            launcher_log: string;
            /** Run Dir */
            run_dir: string;
        };
        /** LineageRefSchema */
        LineageRefSchema: {
            /** Attempt Id */
            attempt_id: string;
            /** Stage Name */
            stage_name: string;
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
        };
        /** LogChunk */
        LogChunk: {
            /** File */
            file: string;
            /** Offset */
            offset: number;
            /** Next Offset */
            next_offset: number;
            /** Eof */
            eof: boolean;
            /** Content */
            content: string;
        };
        /** LogFileInfo */
        LogFileInfo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
            /** Exists */
            exists: boolean;
        };
        /** PluginListResponse */
        PluginListResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "reward" | "validation" | "evaluation" | "reports";
            /** Plugins */
            plugins: components["schemas"]["PluginManifest"][];
        };
        /**
         * PluginManifest
         * @description Normalised manifest surfaced to the web UI.
         */
        PluginManifest: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Stability
             * @default stable
             */
            stability: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "reward" | "validation" | "evaluation" | "reports";
            /** Supported Strategies */
            supported_strategies?: string[];
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** Thresholds Schema */
            thresholds_schema?: {
                [key: string]: unknown;
            };
            /** Suggested Params */
            suggested_params?: {
                [key: string]: unknown;
            };
            /** Suggested Thresholds */
            suggested_thresholds?: {
                [key: string]: unknown;
            };
        };
        /** PresetDiffEntry */
        PresetDiffEntry: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "removed" | "changed" | "unchanged";
            /**
             * Reason
             * @enum {string}
             */
            reason: "preset_replaced" | "preset_added" | "preset_preserved" | "no_scope";
            /** Before */
            before?: unknown;
            /** After */
            after?: unknown;
        };
        /** PresetPlaceholderHint */
        PresetPlaceholderHint: {
            /** Path */
            path: string;
            /** Hint */
            hint: string;
        };
        /** PresetPreviewRequest */
        PresetPreviewRequest: {
            /** Current Config */
            current_config?: {
                [key: string]: unknown;
            };
        };
        /** PresetPreviewResponse */
        PresetPreviewResponse: {
            /** Resulting Config */
            resulting_config: {
                [key: string]: unknown;
            };
            /** Diff */
            diff: components["schemas"]["PresetDiffEntry"][];
            /** Requirements */
            requirements: components["schemas"]["PresetRequirementCheck"][];
            /** Placeholders */
            placeholders: components["schemas"]["PresetPlaceholderHint"][];
            /** Warnings */
            warnings?: string[];
        };
        /** PresetRequirementCheck */
        PresetRequirementCheck: {
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "missing" | "warning";
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * PresetRequirementsOut
         * @description Environmental prerequisites surfaced to the UI.
         */
        PresetRequirementsOut: {
            /** Hub Models */
            hub_models?: string[];
            /** Provider Kind */
            provider_kind?: string[];
            /** Required Plugins */
            required_plugins?: string[];
            /** Min Vram Gb */
            min_vram_gb?: number | null;
        };
        /**
         * PresetScopeOut
         * @description Declared authority of a preset over top-level config keys.
         */
        PresetScopeOut: {
            /** Replaces */
            replaces?: string[];
            /** Preserves */
            preserves?: string[];
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Description */
            description: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Current Config Yaml
             * @default
             */
            current_config_yaml: string;
        };
        /** ProjectEnvRequest */
        ProjectEnvRequest: {
            /** Env */
            env: {
                [key: string]: string;
            };
        };
        /**
         * ProjectEnvResponse
         * @description Project-scoped environment overrides (``HF_TOKEN`` & friends).
         */
        ProjectEnvResponse: {
            /**
             * Env
             * @default {}
             */
            env: {
                [key: string]: string;
            };
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ProviderConfigResponse */
        ProviderConfigResponse: {
            /** Yaml */
            yaml: string;
            /** Parsed Json */
            parsed_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProviderConfigVersion */
        ProviderConfigVersion: {
            /** Filename */
            filename: string;
            /** Created At */
            created_at: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ProviderConfigVersionDetail */
        ProviderConfigVersionDetail: {
            /** Filename */
            filename: string;
            /** Yaml */
            yaml: string;
        };
        /** ProviderConfigVersionsResponse */
        ProviderConfigVersionsResponse: {
            /** Versions */
            versions: components["schemas"]["ProviderConfigVersion"][];
        };
        /** ProviderDetail */
        ProviderDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Path */
            path: string;
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Has Inference
             * @default false
             */
            has_inference: boolean;
            /** Updated At */
            updated_at: string;
            /**
             * Current Config Yaml
             * @default
             */
            current_config_yaml: string;
        };
        /** ProviderSaveConfigRequest */
        ProviderSaveConfigRequest: {
            /** Yaml */
            yaml: string;
        };
        /** ProviderSaveConfigResponse */
        ProviderSaveConfigResponse: {
            /** Ok */
            ok: boolean;
            /** Snapshot Filename */
            snapshot_filename?: string | null;
        };
        /** ProviderSummary */
        ProviderSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Path */
            path: string;
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Has Inference
             * @default false
             */
            has_inference: boolean;
        };
        /** ProviderTypeInfo */
        ProviderTypeInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Json Schema */
            json_schema: {
                [key: string]: unknown;
            };
        };
        /** ProviderTypesResponse */
        ProviderTypesResponse: {
            /** Types */
            types: components["schemas"]["ProviderTypeInfo"][];
        };
        /**
         * ReportDefaultsResponse
         * @description The built-in report-section order used when the pipeline config
         *     doesn't declare ``reports.sections``. Surfaced so the frontend can
         *     pre-fill its reports section with a sensible starting list.
         */
        ReportDefaultsResponse: {
            /** Sections */
            sections: string[];
        };
        /** ReportResponse */
        ReportResponse: {
            /** Path */
            path: string;
            /** Markdown */
            markdown: string;
            /** Generated At */
            generated_at: string;
            /**
             * Regenerated
             * @default false
             */
            regenerated: boolean;
        };
        /** RestartPoint */
        RestartPoint: {
            /** Stage */
            stage: string;
            /** Available */
            available: boolean;
            /** Mode */
            mode: string;
            /** Reason */
            reason: string;
        };
        /** RestartPointsResponse */
        RestartPointsResponse: {
            /** Config Path */
            config_path: string;
            /** Points */
            points?: components["schemas"]["RestartPoint"][];
        };
        /** RunDetail */
        RunDetail: {
            /** Schema Version */
            schema_version: number;
            /** Logical Run Id */
            logical_run_id: string;
            /** Run Directory */
            run_directory: string;
            /** Config Path */
            config_path: string;
            /** Config Abspath */
            config_abspath?: string | null;
            /** Active Attempt Id */
            active_attempt_id?: string | null;
            /** Pipeline Status */
            pipeline_status: string;
            /**
             * Training Critical Config Hash
             * @default
             */
            training_critical_config_hash: string;
            /**
             * Late Stage Config Hash
             * @default
             */
            late_stage_config_hash: string;
            /**
             * Model Dataset Config Hash
             * @default
             */
            model_dataset_config_hash: string;
            /** Root Mlflow Run Id */
            root_mlflow_run_id?: string | null;
            /** Mlflow Runtime Tracking Uri */
            mlflow_runtime_tracking_uri?: string | null;
            /** Mlflow Ca Bundle Path */
            mlflow_ca_bundle_path?: string | null;
            /** Attempts */
            attempts?: {
                [key: string]: unknown;
            }[];
            /** Current Output Lineage */
            current_output_lineage?: {
                [key: string]: components["schemas"]["LineageRefSchema"];
            };
            /** Status */
            status: string;
            /** Status Icon */
            status_icon?: string | null;
            /** Status Color */
            status_color?: string | null;
            /** Running Attempt No */
            running_attempt_no?: number | null;
            /**
             * Next Attempt No
             * @default 1
             */
            next_attempt_no: number;
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
            /** Lock Pid */
            lock_pid?: number | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Run Dir */
            run_dir: string;
            /** Created At */
            created_at: string;
            /** Created Ts */
            created_ts: number;
            /** Status */
            status: string;
            /** Status Icon */
            status_icon?: string | null;
            /** Status Color */
            status_color?: string | null;
            /** Attempts */
            attempts: number;
            /** Config Name */
            config_name: string;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Group
             * @default (root)
             */
            group: string;
        };
        /** RunsListResponse */
        RunsListResponse: {
            /** Runs Dir */
            runs_dir: string;
            /** Groups */
            groups?: {
                [key: string]: components["schemas"]["RunSummary"][];
            };
        };
        /** SaveConfigRequest */
        SaveConfigRequest: {
            /** Yaml */
            yaml: string;
        };
        /** SaveConfigResponse */
        SaveConfigResponse: {
            /** Ok */
            ok: boolean;
            /** Snapshot Filename */
            snapshot_filename?: string | null;
        };
        /** StageRun */
        StageRun: {
            /** Stage Name */
            stage_name: string;
            /** Status */
            status: string;
            /** Status Icon */
            status_icon?: string | null;
            /** Status Color */
            status_color?: string | null;
            /** Execution Mode */
            execution_mode?: string | null;
            /** Mode Label */
            mode_label?: string | null;
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
            /** Failure Kind */
            failure_kind?: string | null;
            /** Reuse From */
            reuse_from?: {
                [key: string]: unknown;
            } | null;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
        };
        /** StagesResponse */
        StagesResponse: {
            /** Stages */
            stages?: components["schemas"]["StageRun"][];
        };
        /** ToggleFavoriteRequest */
        ToggleFavoriteRequest: {
            /** Favorite */
            favorite: boolean;
        };
        /** ToggleFavoriteResponse */
        ToggleFavoriteResponse: {
            /** Favorite Versions */
            favorite_versions: string[];
        };
        /** UpdateProjectDescriptionRequest */
        UpdateProjectDescriptionRequest: {
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "health-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    "config-validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "config-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultConfigResponse"];
                };
            };
        };
    };
    "config-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "config-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigPresetsResponse"];
                };
            };
        };
    };
    "config-preview_preset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "attempts-get_attempt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_no: number;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "attempts-get_stages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_no: number;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "logs-get_log_chunk": {
        parameters: {
            query?: {
                file?: string;
                offset?: number;
                max_bytes?: number;
            };
            header?: never;
            path: {
                attempt_no: number;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogChunk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "logs-list_files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_no: number;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogFileInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "launch-restart_points": {
        parameters: {
            query?: {
                config_path?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartPointsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "launch-default_launch_mode": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "launch-launch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "launch-interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterruptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "plugins-get_report_defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDefaultsResponse"];
                };
            };
        };
    };
    "plugins-list_plugins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "reward" | "validation" | "evaluation" | "reports";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-list_projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    "projects-create_project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-get_project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-delete_project": {
        parameters: {
            query?: {
                delete_files?: boolean;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-update_description": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDescriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-get_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-save_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-get_project_env": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEnvResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-save_project_env": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectEnvRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEnvResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-validate_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-list_versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-read_version": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-restore_version": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-toggle_favorite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleFavoriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleFavoriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-list_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTypesResponse"];
                };
            };
        };
    };
    "providers-list_providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSummary"][];
                };
            };
        };
    };
    "providers-create_provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-get_provider": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-delete_provider": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-get_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-save_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSaveConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSaveConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-validate_config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSaveConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-list_versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigVersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-read_version": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-restore_version": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSaveConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reports-get_report": {
        parameters: {
            query?: {
                regenerate?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-list_runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsListResponse"];
                };
            };
        };
    };
    "runs-create_run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-get_run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-delete_run": {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
