"""Sentinel: ``docs/testing/STATUS.md`` is no older than 14 days.

The status dashboard is auto-generated by ``scripts/testing/status.py``
(invoked via ``make test-status``). If nobody regenerates it for two
weeks, the numbers go stale and the dashboard becomes confidence
theater. This sentinel forces a refresh by failing CI when the file's
mtime is too old.

Refresh path: ``make test-status`` (locally), or rely on a CI scheduled
job (TBD; for now manual).
"""

from __future__ import annotations

import datetime
import os
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
STATUS = REPO_ROOT / "docs" / "testing" / "STATUS.md"

MAX_AGE_DAYS = 14


def test_status_dashboard_is_fresh() -> None:
    if not STATUS.exists():
        pytest.fail(
            f"{STATUS.relative_to(REPO_ROOT)} does not exist. Generate it via "
            f"`make test-status` (or `python scripts/testing/status.py`)."
        )
    mtime = datetime.datetime.fromtimestamp(STATUS.stat().st_mtime, datetime.UTC)
    age = datetime.datetime.now(datetime.UTC) - mtime
    if age.days > MAX_AGE_DAYS:
        pytest.fail(
            f"{STATUS.relative_to(REPO_ROOT)} is {age.days} days old "
            f"(max {MAX_AGE_DAYS}). Regenerate via `make test-status`."
        )
