"""Concrete event type re-exports.

This module re-exports every concrete ``*Event`` and ``*Payload`` class
from the type-domain submodules. The discriminated union itself is
assembled in :mod:`ryotenkai_shared.events.discriminator` so that this
``__init__`` stays a flat namespace (and so that import cycles between
the union and the catch-all :class:`UnknownEvent` are avoided).

Listing each name explicitly is more verbose than ``from .x import *``
but it gives mypy/IDEs a concrete symbol table to work from and makes
"what events exist" answerable by reading one file.
"""

from __future__ import annotations

from ryotenkai_shared.events.types.control_dataset import (
    DatasetValidationCompletedEvent,
    DatasetValidationCompletedPayload,
    DatasetValidationFailedEvent,
    DatasetValidationFailedPayload,
    DatasetValidationPluginCompletedEvent,
    DatasetValidationPluginCompletedPayload,
    DatasetValidationPluginFailedEvent,
    DatasetValidationPluginFailedPayload,
    DatasetValidationPluginStartedEvent,
    DatasetValidationPluginStartedPayload,
    DatasetValidationStartedEvent,
    DatasetValidationStartedPayload,
)
from ryotenkai_shared.events.types.control_evaluation import (
    EvaluationCompletedEvent,
    EvaluationCompletedPayload,
    EvaluationPluginCompletedEvent,
    EvaluationPluginCompletedPayload,
    EvaluationPluginFailedEvent,
    EvaluationPluginFailedPayload,
    EvaluationPluginStartedEvent,
    EvaluationPluginStartedPayload,
    EvaluationStartedEvent,
    EvaluationStartedPayload,
)
from ryotenkai_shared.events.types.control_gpu import (
    CleanupProvider,
    CleanupReason,
    GpuCleanupCompletedEvent,
    GpuCleanupCompletedPayload,
    GpuCleanupFailedEvent,
    GpuCleanupFailedPayload,
    GpuCleanupStartedEvent,
    GpuCleanupStartedPayload,
    GPUCodeSyncedEvent,
    GPUCodeSyncedPayload,
    GPUDeploymentCompletedEvent,
    GPUDeploymentCompletedPayload,
    GPUDeploymentFailedEvent,
    GPUDeploymentFailedPayload,
    GPUDeploymentStartedEvent,
    GPUDeploymentStartedPayload,
    GPUPreemptedEvent,
    GPUPreemptedPayload,
    GPUSSHProvisionedEvent,
    GPUSSHProvisionedPayload,
)
from ryotenkai_shared.events.types.control_inference import (
    InferenceDeactivatedEvent,
    InferenceDeactivatedPayload,
    InferenceDeployedEvent,
    InferenceDeployedPayload,
    InferenceDeploymentFailedEvent,
    InferenceDeploymentFailedPayload,
    InferenceDeploymentStartedEvent,
    InferenceDeploymentStartedPayload,
    InferenceHealthCheckCompletedEvent,
    InferenceHealthCheckCompletedPayload,
    InferenceHealthCheckStartedEvent,
    InferenceHealthCheckStartedPayload,
    InferenceTarget,
)
from ryotenkai_shared.events.types.control_model import (
    MetricsBufferOversizedEvent,
    MetricsBufferOversizedPayload,
    ModelMetricsBufferRetrievedEvent,
    ModelMetricsBufferRetrievedPayload,
    ModelRetrievalCompletedEvent,
    ModelRetrievalCompletedPayload,
    ModelRetrievalStartedEvent,
    ModelRetrievalStartedPayload,
)
from ryotenkai_shared.events.types.control_run import (
    RunCancelledEvent,
    RunCancelledPayload,
    RunCompletedEvent,
    RunCompletedPayload,
    RunFailedEvent,
    RunFailedPayload,
    RunStartedEvent,
    RunStartedPayload,
)
from ryotenkai_shared.events.types.control_stage import (
    StageCompletedEvent,
    StageCompletedPayload,
    StageFailedEvent,
    StageFailedPayload,
    StageInterruptedEvent,
    StageInterruptedPayload,
    StageSkippedEvent,
    StageSkippedPayload,
    StageStartedEvent,
    StageStartedPayload,
)
from ryotenkai_shared.events.types.control_training import (
    TrainingMonitorStartedEvent,
    TrainingMonitorStartedPayload,
    TrainingMonitorTimeoutEvent,
    TrainingMonitorTimeoutPayload,
)
from ryotenkai_shared.events.types.pod_health import (
    GPUSnapshot,
    HealthIdleDetectedEvent,
    HealthIdleDetectedPayload,
    HealthMaxLifetimeExceededEvent,
    HealthMaxLifetimeExceededPayload,
    HealthMaxLifetimeReachedEvent,
    HealthMaxLifetimeReachedPayload,
    HealthSnapshotEvent,
    HealthSnapshotPayload,
)
from ryotenkai_shared.events.types.pod_io import (
    IOStream,
    TrainerStderrEvent,
    TrainerStderrPayload,
    TrainerStdoutEvent,
    TrainerStdoutPayload,
)
from ryotenkai_shared.events.types.pod_journal import (
    JournalDiskPressureEvent,
    JournalDiskPressurePayload,
    JournalRotatedEvent,
    JournalRotatedPayload,
)
from ryotenkai_shared.events.types.pod_lifecycle import (
    JobSubmittedEvent,
    JobSubmittedPayload,
    PluginsUnpackedEvent,
    PluginsUnpackedPayload,
    RunnerShutdownEvent,
    RunnerShutdownPayload,
    RunnerStartedEvent,
    RunnerStartedPayload,
    StopRequestedEvent,
    StopRequestedPayload,
    TrainerExitedEvent,
    TrainerExitedPayload,
    TrainerSpawnedEvent,
    TrainerSpawnedPayload,
    TrainerSpawnFailedEvent,
    TrainerSpawnFailedPayload,
)
from ryotenkai_shared.events.types.pod_memory import (
    CacheClearTrigger,
    MemoryCacheClearedEvent,
    MemoryCacheClearedPayload,
    MemoryOOMDetectedEvent,
    MemoryOOMDetectedPayload,
    MemoryPressureWarningEvent,
    MemoryPressureWarningPayload,
    MemoryThresholdReachedEvent,
    MemoryThresholdReachedPayload,
)
from ryotenkai_shared.events.types.pod_training import (
    Algorithm,
    TrainingCheckpointSavedEvent,
    TrainingCheckpointSavedPayload,
    TrainingCompletedEvent,
    TrainingCompletedPayload,
    TrainingEpochCompletedEvent,
    TrainingEpochCompletedPayload,
    TrainingEpochStartedEvent,
    TrainingEpochStartedPayload,
    TrainingEvalMetricsEvent,
    TrainingEvalMetricsPayload,
    TrainingFailedEvent,
    TrainingFailedPayload,
    TrainingLogEvent,
    TrainingLogPayload,
    TrainingStartedEvent,
    TrainingStartedPayload,
    TrainingStepEvent,
    TrainingStepPayload,
)
from ryotenkai_shared.events.types.unknown import UnknownEvent

__all__ = [  # noqa: RUF022 — grouped by domain for readability, not alphabetised
    # Aliases & literals
    "Algorithm",
    "CacheClearTrigger",
    "CleanupProvider",
    "CleanupReason",
    "IOStream",
    "InferenceTarget",
    "GPUSnapshot",
    # Pod lifecycle
    "RunnerStartedPayload",
    "RunnerStartedEvent",
    "RunnerShutdownPayload",
    "RunnerShutdownEvent",
    "JobSubmittedPayload",
    "JobSubmittedEvent",
    "TrainerSpawnedPayload",
    "TrainerSpawnedEvent",
    "TrainerSpawnFailedPayload",
    "TrainerSpawnFailedEvent",
    "TrainerExitedPayload",
    "TrainerExitedEvent",
    "StopRequestedPayload",
    "StopRequestedEvent",
    "PluginsUnpackedPayload",
    "PluginsUnpackedEvent",
    # Pod journal
    "JournalRotatedPayload",
    "JournalRotatedEvent",
    "JournalDiskPressurePayload",
    "JournalDiskPressureEvent",
    # Pod training
    "TrainingStartedPayload",
    "TrainingStartedEvent",
    "TrainingEpochStartedPayload",
    "TrainingEpochStartedEvent",
    "TrainingEpochCompletedPayload",
    "TrainingEpochCompletedEvent",
    "TrainingStepPayload",
    "TrainingStepEvent",
    "TrainingLogPayload",
    "TrainingLogEvent",
    "TrainingEvalMetricsPayload",
    "TrainingEvalMetricsEvent",
    "TrainingCheckpointSavedPayload",
    "TrainingCheckpointSavedEvent",
    "TrainingCompletedPayload",
    "TrainingCompletedEvent",
    "TrainingFailedPayload",
    "TrainingFailedEvent",
    # Pod memory
    "MemoryCacheClearedPayload",
    "MemoryCacheClearedEvent",
    "MemoryOOMDetectedPayload",
    "MemoryOOMDetectedEvent",
    "MemoryPressureWarningPayload",
    "MemoryPressureWarningEvent",
    "MemoryThresholdReachedPayload",
    "MemoryThresholdReachedEvent",
    # Pod health
    "HealthSnapshotPayload",
    "HealthSnapshotEvent",
    "HealthIdleDetectedPayload",
    "HealthIdleDetectedEvent",
    "HealthMaxLifetimeReachedPayload",
    "HealthMaxLifetimeReachedEvent",
    "HealthMaxLifetimeExceededPayload",
    "HealthMaxLifetimeExceededEvent",
    # Pod IO
    "TrainerStdoutPayload",
    "TrainerStdoutEvent",
    "TrainerStderrPayload",
    "TrainerStderrEvent",
    # Control run
    "RunStartedPayload",
    "RunStartedEvent",
    "RunCompletedPayload",
    "RunCompletedEvent",
    "RunFailedPayload",
    "RunFailedEvent",
    "RunCancelledPayload",
    "RunCancelledEvent",
    # Control stage
    "StageStartedPayload",
    "StageStartedEvent",
    "StageCompletedPayload",
    "StageCompletedEvent",
    "StageFailedPayload",
    "StageFailedEvent",
    "StageSkippedPayload",
    "StageSkippedEvent",
    "StageInterruptedPayload",
    "StageInterruptedEvent",
    # Control dataset
    "DatasetValidationStartedPayload",
    "DatasetValidationStartedEvent",
    "DatasetValidationCompletedPayload",
    "DatasetValidationCompletedEvent",
    "DatasetValidationFailedPayload",
    "DatasetValidationFailedEvent",
    "DatasetValidationPluginStartedPayload",
    "DatasetValidationPluginStartedEvent",
    "DatasetValidationPluginCompletedPayload",
    "DatasetValidationPluginCompletedEvent",
    "DatasetValidationPluginFailedPayload",
    "DatasetValidationPluginFailedEvent",
    # Control gpu
    "GPUDeploymentStartedPayload",
    "GPUDeploymentStartedEvent",
    "GPUDeploymentCompletedPayload",
    "GPUDeploymentCompletedEvent",
    "GPUDeploymentFailedPayload",
    "GPUDeploymentFailedEvent",
    "GPUPreemptedPayload",
    "GPUPreemptedEvent",
    "GPUSSHProvisionedPayload",
    "GPUSSHProvisionedEvent",
    "GPUCodeSyncedPayload",
    "GPUCodeSyncedEvent",
    "GpuCleanupStartedPayload",
    "GpuCleanupStartedEvent",
    "GpuCleanupCompletedPayload",
    "GpuCleanupCompletedEvent",
    "GpuCleanupFailedPayload",
    "GpuCleanupFailedEvent",
    # Control training (monitor)
    "TrainingMonitorStartedPayload",
    "TrainingMonitorStartedEvent",
    "TrainingMonitorTimeoutPayload",
    "TrainingMonitorTimeoutEvent",
    # Control model
    "ModelRetrievalStartedPayload",
    "ModelRetrievalStartedEvent",
    "ModelRetrievalCompletedPayload",
    "ModelRetrievalCompletedEvent",
    "ModelMetricsBufferRetrievedPayload",
    "ModelMetricsBufferRetrievedEvent",
    "MetricsBufferOversizedPayload",
    "MetricsBufferOversizedEvent",
    # Control evaluation
    "EvaluationStartedPayload",
    "EvaluationStartedEvent",
    "EvaluationPluginStartedPayload",
    "EvaluationPluginStartedEvent",
    "EvaluationPluginCompletedPayload",
    "EvaluationPluginCompletedEvent",
    "EvaluationPluginFailedPayload",
    "EvaluationPluginFailedEvent",
    "EvaluationCompletedPayload",
    "EvaluationCompletedEvent",
    # Control inference
    "InferenceDeploymentStartedPayload",
    "InferenceDeploymentStartedEvent",
    "InferenceHealthCheckStartedPayload",
    "InferenceHealthCheckStartedEvent",
    "InferenceHealthCheckCompletedPayload",
    "InferenceHealthCheckCompletedEvent",
    "InferenceDeployedPayload",
    "InferenceDeployedEvent",
    "InferenceDeactivatedPayload",
    "InferenceDeactivatedEvent",
    "InferenceDeploymentFailedPayload",
    "InferenceDeploymentFailedEvent",
    # Forward-compat
    "UnknownEvent",
]
