/**
 * Phase 3 (Contract Testing Matrix) demo: exercises an API call through
 * MSW and the runtime contract guard.
 *
 * What this test asserts:
 * 1. Booting the MSW Node server in ``src/test/setup.ts`` actually
 *    intercepts ``fetch`` requests made by the existing ``api`` client.
 * 2. The contract-shaped synthesised handler for ``GET /projects``
 *    (auto-generated by ``scripts/gen-msw.mjs``) is shaped well enough
 *    to pass the zod schema in ``useProjects``.
 * 3. A consumer component re-renders with the response — which proves
 *    React Query is wired to ``api`` correctly, and that
 *    ``validateResponse`` doesn't accidentally throw on the synthesised
 *    payload.
 *
 * Phase 3 explicitly only wires ONE endpoint through ``validateResponse``
 * (``useProjects``), so this is the first "fully through the contract
 * gate" test. Wider rollout is tracked in the TODO in ``useProjects.ts``.
 */

import { describe, expect, it } from 'vitest'
import { http, HttpResponse } from 'msw'
import { render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { server } from '../../test/setup'
import { useProjects } from '../../api/hooks/useProjects'

function ProjectsList() {
  const { data, isLoading } = useProjects()
  if (isLoading) return <div data-testid="loading">loading</div>
  return (
    <ul data-testid="projects-list">
      {(data ?? []).map((p) => (
        <li key={p.id} data-testid="project-row">
          {p.id}
        </li>
      ))}
    </ul>
  )
}

function renderWithClient() {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false, gcTime: 0 } },
  })
  return render(
    <QueryClientProvider client={client}>
      <ProjectsList />
    </QueryClientProvider>,
  )
}

describe('useProjects + MSW (Phase 3 contract demo)', () => {
  it('renders the synthesised default (empty list) from the auto-generated handler', async () => {
    renderWithClient()
    await waitFor(() => {
      expect(screen.getByTestId('projects-list')).toBeInTheDocument()
    })
    // The auto-generated handler returns ``[]`` (schema's zero value for
    // ``array``), so the list renders with no rows.
    expect(screen.queryAllByTestId('project-row')).toHaveLength(0)
  })

  it('renders rows from a per-test override of the MSW handler', async () => {
    // Override the auto-generated 200 with a contract-shaped fixture so
    // we can assert the render path with non-trivial data. The override
    // is scoped to this test by ``afterEach(server.resetHandlers)``.
    server.use(
      http.get('/api/v1/projects', () =>
        HttpResponse.json([
          {
            id: 'demo-project',
            name: 'demo',
            path: '/tmp/demo',
            created_at: '2026-01-01T00:00:00Z',
            description: '',
          },
        ]),
      ),
    )

    renderWithClient()
    await waitFor(() => {
      expect(screen.getByText('demo-project')).toBeInTheDocument()
    })
  })
})
