"""Timeouts, truncation limits, and SSH-side constants used by TrainingDeploymentManager.

Lives next to deployment_manager.py — they are deployment-specific and
nobody else reads them. Pulling them out of pipeline.constants keeps the
top-level constants module to genuinely cross-cutting values only.
"""

from __future__ import annotations

from src.constants import ERROR_MESSAGE_TRUNCATE, SSH_CMD_TIMEOUT, TRAINING_START_TIMEOUT_DEFAULT

DEPLOYMENT_RSYNC_TIMEOUT = 120
DEPLOYMENT_SSH_CMD_TIMEOUT = SSH_CMD_TIMEOUT
DEPLOYMENT_TAR_TIMEOUT = 60
DEPLOYMENT_VERIFY_TIMEOUT = 10
DEPLOYMENT_DOCKER_PULL_TIMEOUT = 1200
DEPLOYMENT_PYTHON_VERIFY_TIMEOUT = 60
DEPLOYMENT_DOCKER_VERIFY_TIMEOUT = 120
DEPLOYMENT_SCRIPT_CHMOD_TIMEOUT = SSH_CMD_TIMEOUT
DEPLOYMENT_LAUNCH_TIMEOUT = SSH_CMD_TIMEOUT
DEPLOYMENT_ERROR_TRUNCATE = ERROR_MESSAGE_TRUNCATE
DEPLOYMENT_LOG_TRUNCATE = 500
DEPLOYMENT_STDERR_TRUNCATE = 300
DEPLOYMENT_STDOUT_LINES = 20
DEPLOYMENT_CONTAINER_NAME_MAX_LEN = 80
DEPLOYMENT_TRAINING_START_TIMEOUT = TRAINING_START_TIMEOUT_DEFAULT
DEPLOYMENT_PS_AUX_LINES = 11
DEPLOYMENT_MARKER_EXISTS = "EXISTS"
DEPLOYMENT_CONFIG_PATH = "config/pipeline_config.yaml"
DEPLOYMENT_MODE_KEY = "mode"
DEPLOYMENT_DOCKER_VALUE = "docker"


__all__ = [
    "DEPLOYMENT_CONFIG_PATH",
    "DEPLOYMENT_CONTAINER_NAME_MAX_LEN",
    "DEPLOYMENT_DOCKER_PULL_TIMEOUT",
    "DEPLOYMENT_DOCKER_VALUE",
    "DEPLOYMENT_DOCKER_VERIFY_TIMEOUT",
    "DEPLOYMENT_ERROR_TRUNCATE",
    "DEPLOYMENT_LAUNCH_TIMEOUT",
    "DEPLOYMENT_LOG_TRUNCATE",
    "DEPLOYMENT_MARKER_EXISTS",
    "DEPLOYMENT_MODE_KEY",
    "DEPLOYMENT_PS_AUX_LINES",
    "DEPLOYMENT_PYTHON_VERIFY_TIMEOUT",
    "DEPLOYMENT_RSYNC_TIMEOUT",
    "DEPLOYMENT_SCRIPT_CHMOD_TIMEOUT",
    "DEPLOYMENT_SSH_CMD_TIMEOUT",
    "DEPLOYMENT_STDERR_TRUNCATE",
    "DEPLOYMENT_STDOUT_LINES",
    "DEPLOYMENT_TAR_TIMEOUT",
    "DEPLOYMENT_TRAINING_START_TIMEOUT",
    "DEPLOYMENT_VERIFY_TIMEOUT",
]
