"""Constants for providers (SSH, RunPod, etc.)."""

from src.constants import (
    TRAINING_START_TIMEOUT_DEFAULT,
)

# SSH connect
SSH_MAX_RETRIES_DEFAULT = 3
SSH_MAX_RETRIES_MIN = 1
SSH_MAX_RETRIES_MAX = 10

SSH_RETRY_DELAY_MIN = 1
SSH_RETRY_DELAY_MAX = 60
SSH_RETRY_DELAY_DEFAULT = 10

SSH_TIMEOUT_MIN = 5
SSH_TIMEOUT_MAX = 600
SSH_TIMEOUT_DEFAULT = 180

# SSH port
SSH_PORT_DEFAULT = 22
SSH_PORT_MIN = 1
SSH_PORT_MAX = 65535

# RunPod (inference + training)
RUNPOD_VOLUME_SIZE_GB_MIN = 1
RUNPOD_VOLUME_SIZE_GB_MAX = 4000
RUNPOD_VOLUME_SIZE_GB_DEFAULT = 50

RUNPOD_CONTAINER_DISK_GB_MIN = 10
RUNPOD_CONTAINER_DISK_GB_MAX = 500
RUNPOD_CONTAINER_DISK_GB_DEFAULT = 50

RUNPOD_SERVE_PORT_MIN = 1
RUNPOD_SERVE_PORT_MAX = 65535
RUNPOD_SERVE_PORT_DEFAULT = 8000

RUNPOD_TRAINING_VOLUME_DISK_GB_DEFAULT = 20

# Pod Volume (inference without network volume)
RUNPOD_POD_VOLUME_GB_DEFAULT = 50

# Single-node
SINGLE_NODE_TRAINING_START_TIMEOUT_MIN = 10
SINGLE_NODE_TRAINING_START_TIMEOUT_MAX = 600
SINGLE_NODE_TRAINING_START_TIMEOUT_DEFAULT = TRAINING_START_TIMEOUT_DEFAULT
