"""Constants for inference config (health check, chat UI, etc.)."""

# Health check
HEALTH_CHECK_TIMEOUT_MIN = 5
HEALTH_CHECK_TIMEOUT_MAX = 3600
HEALTH_CHECK_TIMEOUT_DEFAULT = 120

HEALTH_CHECK_INTERVAL_MIN = 1
HEALTH_CHECK_INTERVAL_MAX = 120
HEALTH_CHECK_INTERVAL_DEFAULT = 5

HEALTH_CHECK_RETRIES_MIN = 1
HEALTH_CHECK_RETRIES_MAX = 20
HEALTH_CHECK_RETRIES_DEFAULT = 3

# Chat UI (Gradio default port, TCP max)
CHAT_UI_PORT_MIN = 1
CHAT_UI_PORT_MAX = 65535
CHAT_UI_PORT_DEFAULT = 7860

# Single-node serve (vLLM default port, TCP max)
SINGLE_NODE_PORT_MIN = 1
SINGLE_NODE_PORT_MAX = 65535
SINGLE_NODE_PORT_DEFAULT = 8000

# vLLM engine
MAX_MODEL_LEN_MIN = 256
MAX_MODEL_LEN_DEFAULT = 4096

GPU_MEMORY_UTILIZATION_DEFAULT = 0.90
