#!/usr/bin/env python3
"""Generate ``docs/testing/STATUS.md`` — auto-refreshable test-infra dashboard.

Run via ``make test-status`` (or directly). Emits a Markdown summary
of every load-bearing gate so the user can scan it in 30 seconds:

- Lane size (tests collected) + xfail count
- Sentinel matrix
- Mock inventory snapshot (count + allowlist size)
- Mutation testing kill rates per hotspot (from ratchet baseline)
- xfail debt ledger entry count
- Last-known data timestamps so staleness is visible

The output file's mtime is checked by
``tests/_lint/test_status_freshness.py`` — if it's > 14 days old, CI
fails. This forces the dashboard to stay current.
"""

from __future__ import annotations

import datetime
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "testing" / "STATUS.md"
RATCHET = REPO_ROOT / "scripts" / "mutation" / "ratchet_baseline.json"
HOTSPOTS = REPO_ROOT / ".mutation-hotspots.yml"
XFAIL_DEBT = REPO_ROOT / "docs" / "migration" / "xfail_debt.md"
ALLOWLIST = REPO_ROOT / "tests" / "_lint" / "_mock_allowlist.py"


def _now_utc() -> str:
    return datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _collect_count() -> dict[str, int]:
    """Counts from ``pytest --collect-only -q`` on each lane."""
    out: dict[str, int] = {}
    for lane in ("tests/unit", "tests/integration", "tests/e2e", "tests/_lint"):
        try:
            r = subprocess.run(
                [sys.executable, "-m", "pytest", lane, "--collect-only", "-q", "-p", "no:cacheprovider"],
                capture_output=True,
                text=True,
                cwd=REPO_ROOT,
                timeout=120,
            )
        except subprocess.TimeoutExpired:
            out[lane] = -1
            continue
        last = next((ln for ln in reversed(r.stdout.splitlines()) if ln.strip()), "")
        m = re.search(r"(\d+) tests? collected", last)
        out[lane] = int(m.group(1)) if m else -1
    return out


def _xfail_inventory() -> dict[str, int]:
    """Count strict-True / strict-False xfails in the tests tree."""
    try:
        r = subprocess.run(
            ["grep", "-rn", "pytest.mark.xfail", str(REPO_ROOT / "tests")],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return {"strict_true": -1, "total_markers": -1}
    lines = [ln for ln in r.stdout.splitlines() if "xfail" in ln]
    total = len([ln for ln in lines if "@pytest.mark.xfail" in ln or "pytestmark = pytest.mark.xfail" in ln])
    strict_true = 0
    for ln in lines:
        if "strict=True" in ln:
            strict_true += 1
    return {"strict_true": strict_true, "total_markers": total}


def _ratchet_baseline() -> dict:
    if not RATCHET.exists():
        return {}
    return json.loads(RATCHET.read_text(encoding="utf-8"))


def _hotspot_mode() -> str:
    if not HOTSPOTS.exists():
        return "?"
    for ln in HOTSPOTS.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if s.startswith("mode:"):
            return s.split(":", 1)[1].strip().split("#", 1)[0].strip()
    return "?"


def _xfail_debt_rows() -> int:
    if not XFAIL_DEBT.exists():
        return 0
    text = XFAIL_DEBT.read_text(encoding="utf-8")
    return text.count("xfail-debt entries")


def _allowlist_size() -> dict[str, int]:
    if not ALLOWLIST.exists():
        return {"entries": 0}
    # Register the module name BEFORE exec so @dataclass can resolve.
    spec = importlib.util.spec_from_file_location("_mock_allowlist", ALLOWLIST)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_mock_allowlist"] = mod
    try:
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
    except Exception:
        sys.modules.pop("_mock_allowlist", None)
        return {"entries": -1, "stale_warn": -1}
    entries = getattr(mod, "ALLOWLIST", [])
    today = datetime.date.today()
    stale_count = 0
    for e in entries:
        try:
            renewed = datetime.date.fromisoformat(e.renewed)
        except ValueError:
            continue
        if (today - renewed).days > 300:
            stale_count += 1
    return {"entries": len(entries), "stale_warn": stale_count}


def main() -> int:
    now = _now_utc()
    coll = _collect_count()
    xfails = _xfail_inventory()
    base = _ratchet_baseline()
    mode = _hotspot_mode()
    debt = _xfail_debt_rows()
    al = _allowlist_size()

    lines = [
        "# Test Infrastructure Status",
        "",
        f"> Auto-generated by `scripts/testing/status.py` at {now}",
        f"> Stale if not regenerated within 14 days (sentinel: `tests/_lint/test_status_freshness.py`).",
        "",
        "## Collection counts",
        "",
        "| Lane | Tests collected |",
        "|---|---:|",
    ]
    for lane, n in coll.items():
        lines.append(f"| `{lane}` | {n if n >= 0 else 'N/A'} |")

    lines += [
        "",
        "## xfail inventory",
        "",
        f"- `@pytest.mark.xfail` markers (total): {xfails['total_markers']}",
        f"- `strict=True` markers: {xfails['strict_true']}",
        f"- xfail-debt ledger sections: {debt}",
        "",
        "## Mutation testing",
        "",
        f"- Mode: **{mode}**",
        f"- Baseline file: `{RATCHET.relative_to(REPO_ROOT)}`",
        f"- Baselined hotspots: {len(base.get('files', {}))}",
        "",
        "| File | Baseline kill rate |",
        "|---|---:|",
    ]
    for path, rate in sorted(base.get("files", {}).items()):
        lines.append(f"| `{path}` | {rate:.2%} |")

    lines += [
        "",
        "## Mock allowlist health",
        "",
        f"- Total entries: {al.get('entries', '?')}",
        f"- Entries > 300 days old (will decay at 365): {al.get('stale_warn', '?')}",
        "",
        "## Sentinel suite",
        "",
        "All sentinels live under `tests/_lint/`. Run via `pytest tests/_lint -q`.",
        "",
        "| Sentinel | What it guards |",
        "|---|---|",
        "| `test_no_protocol_mocking.py` | Mock-elimination policy enforcement |",
        "| `test_xfail_debt_completeness.py` | Strict-True xfails carry tracked tokens |",
        "| `test_allowlist_decay_verified.py` | 365-day decay mechanism works |",
        "| `test_protocol_discovery_invariants.py` | Dynamic Protocol discovery healthy |",
        "| `test_every_module_has_tests.py` | New production modules have test refs |",
        "| `test_clean_collection.py` | Every test tree collects without errors |",
        "| `test_status_freshness.py` | This dashboard is regenerated regularly |",
        "",
        "## Next gates to flip",
        "",
        f"- Mutation `mode` is currently **{mode}**.",
        "  Flip to `blocking` happens automatically via",
        "  `.github/workflows/mutation-flip-check.yml` (weekly) once",
        "  4 nightly runs are green AND 14 days pass without a per-PR",
        "  mutation failure.",
        "",
        "## Generation provenance",
        "",
        "Source-data timestamps (so staleness is visible):",
        "",
        f"- `{RATCHET.relative_to(REPO_ROOT)}` mtime: {datetime.datetime.fromtimestamp(RATCHET.stat().st_mtime, datetime.UTC).isoformat() if RATCHET.exists() else 'N/A'}",
        f"- `{HOTSPOTS.relative_to(REPO_ROOT)}` mtime: {datetime.datetime.fromtimestamp(HOTSPOTS.stat().st_mtime, datetime.UTC).isoformat() if HOTSPOTS.exists() else 'N/A'}",
        f"- `{XFAIL_DEBT.relative_to(REPO_ROOT)}` mtime: {datetime.datetime.fromtimestamp(XFAIL_DEBT.stat().st_mtime, datetime.UTC).isoformat() if XFAIL_DEBT.exists() else 'N/A'}",
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
