"""Trainer subprocess structured exit payload — Phase D.

Cross-process protocol between the trainer subprocess and the runner
supervisor. The trainer writes :file:`trainer-exit.json` to its working
directory on failure (atexit handler) and the supervisor reads it on
reap so the ``trainer_exited`` EventBus event can carry typed
information (``code``, ``message``, ``traceback_summary``) instead of
the legacy ``{exit_code, signal}`` pair.

References
----------
- Plan: ``docs/plans/sharded-stargazing-wigderson.md`` Layer 6 + R-SIGKILL
- :class:`ryotenkai_shared.contracts.problem_details.ErrorCode` — the
  code enum the payload pins on.

Lifecycle
---------
1. Trainer wraps top-level execution in try/except. On
   :class:`RyotenkAIError` → writes payload with ``code=exc.code``;
   on generic :class:`Exception` → writes payload with
   ``code=INTERNAL_ERROR``. On clean exit (rc=0) → does NOT write.
2. Supervisor reaps. If file present + valid Pydantic → use payload.
   If absent + ``exit_code == 0`` → success. If absent + SIGKILL
   (137 / -9) → synthesise ``code=TRAINING_OOM`` (R-SIGKILL
   heuristic — false-positive OOM beats noisy INTERNAL_ERROR for the
   common cgroup-OOM case). Otherwise → ``INTERNAL_ERROR`` with
   ``message="trainer exited without payload, exit_code=<N>"``.

Security
--------
Tracebacks pass through :func:`sanitize_traceback` which strips
absolute filesystem paths (``/Users/.../site-packages/``,
``/home/.../``, ``/tmp/...``) and caps at 30 lines so the wire
payload never leaks server environment topology.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Final

from pydantic import BaseModel, ConfigDict, Field

from ryotenkai_shared.contracts.problem_details import ErrorCode

__all__ = [
    "TRAINER_EXIT_FILENAME",
    "TRAINER_EXIT_SCHEMA_VERSION",
    "TrainerExitPayload",
    "sanitize_traceback",
]


# Standard filename the trainer writes and supervisor reads. Lives
# under the trainer subprocess's working directory (the ``workdir``
# argument of :meth:`Supervisor.submit_and_spawn`) — same place the
# trainer is launched, so both sides agree on the absolute path
# without an extra env var.
TRAINER_EXIT_FILENAME: Final[str] = "trainer-exit.json"

# Schema version pinned in the payload + carried into the EventBus
# ``trainer_exited`` event (which bumps to ``schema_version=2``
# because the legacy ``{exit_code, signal}`` payload was the
# implicit v1 wire shape).
TRAINER_EXIT_SCHEMA_VERSION: Final[int] = 1


# Regex patterns for traceback sanitization. Order matters: longest /
# most specific patterns first so they consume the trailing path
# remainder before the generic ``/Users/<user>/`` rule fires.
_PATH_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    # site-packages on a virtualenv (Mac / Linux / Windows-via-WSL)
    (re.compile(r"/(?:Users|home)/[^/]+/[^/]*\.venv/lib/python[^/]+/site-packages/"), "<sp>/"),
    (re.compile(r"/(?:Users|home)/[^/]+/[^/]*site-packages/"), "<sp>/"),
    (re.compile(r"/usr/(?:local/)?lib/python[^/]+/(?:dist|site)-packages/"), "<sp>/"),
    (re.compile(r"/opt/[^/]+/lib/python[^/]+/site-packages/"), "<sp>/"),
    # generic user / tmp paths
    (re.compile(r"/Users/[^/]+/"), "<home>/"),
    (re.compile(r"/home/[^/]+/"), "<home>/"),
    (re.compile(r"/tmp/[^\s\"']+"), "<tmp>"),
    (re.compile(r"/var/folders/[^\s\"']+"), "<tmp>"),
)

# Hard cap on traceback length (lines). Keeps the on-wire payload
# small and bounds the supervisor's :meth:`Path.read_text` work.
DEFAULT_TRACEBACK_MAX_LINES: Final[int] = 30


def sanitize_traceback(
    tb: str,
    *,
    max_lines: int = DEFAULT_TRACEBACK_MAX_LINES,
) -> str:
    """Strip absolute filesystem paths and cap line count.

    Security boundary: tracebacks generated by Python on a remote pod
    expose the pod-side filesystem layout (``/root/...``, container
    paths, ``/Users/foo/.venv/...``). Those paths are never useful to
    the client and routinely leak operator usernames + virtualenv
    locations. Strip them via regex BEFORE the payload is serialised
    to JSON; the on-disk and on-wire forms are both sanitised.

    Args:
        tb: Raw traceback string (typically :func:`traceback.format_exc`
            output, but any string is accepted).
        max_lines: Maximum number of lines retained. The TAIL is kept
            (the last frames are usually the interesting ones —
            ``self._do_thing()`` raised, not the
            ``orchestrator.run()`` entry).

    Returns:
        Sanitised string. If ``tb`` is empty, returns an empty string.
        Always safe to embed in JSON (no embedded NUL or DEL chars).
    """
    if not tb:
        return ""

    cleaned = tb
    for pattern, replacement in _PATH_PATTERNS:
        cleaned = pattern.sub(replacement, cleaned)

    # Strip stray control chars (defensive — Python tracebacks never
    # contain them, but a third-party logger or signal handler might
    # have written into ``stderr`` between the exception and our
    # ``format_exc`` capture).
    cleaned = "".join(ch for ch in cleaned if ch == "\n" or ch == "\t" or ord(ch) >= 0x20)

    lines = cleaned.splitlines()
    if len(lines) > max_lines:
        # Keep the tail (deepest frames). Prepend a marker so the
        # consumer knows truncation happened — useful for "did the
        # full traceback contain X" debugging.
        kept = lines[-max_lines:]
        kept.insert(0, f"... [traceback truncated: {len(lines) - max_lines} earlier lines elided]")
        return "\n".join(kept)
    return "\n".join(lines)


class TrainerExitPayload(BaseModel):
    """Structured trainer exit envelope.

    Written by the trainer's atexit handler to
    ``<workdir>/trainer-exit.json``; read by :class:`Supervisor` on
    subprocess reap. Both sides depend on the Pydantic model for
    schema enforcement (``extra="forbid"`` rejects rogue keys, so an
    older runner reading a newer payload fails closed rather than
    silently dropping fields).

    Field policy:

    * ``code`` — :class:`ErrorCode` value; pinned on the failure type.
      For ``RyotenkAIError`` it's ``exc.code``; for generic
      ``Exception`` it falls back to ``INTERNAL_ERROR``.
    * ``message`` — short, single-line human description. NEVER
      contains a traceback — that's :attr:`traceback_summary`.
    * ``traceback_summary`` — sanitised tail of
      :func:`traceback.format_exc` output. ``None`` when no traceback
      is available (e.g. the trainer wrote the payload from a clean
      ``raise SystemExit(code)`` path).
    * ``exit_code`` — the rc Python would pass to :func:`os._exit`.
      Carried for parity with the supervisor's
      ``Process.returncode`` reading so both sides can cross-check.
    * ``wall_seconds`` — total wall-clock seconds from trainer start
      to atexit handler firing. Lets the supervisor populate
      ``duration_seconds`` even when the EventBus side missed
      ``trainer_spawned`` (rare; only matters for forensics).
    * ``schema_version`` — bumped when the field set changes. The
      supervisor's reader accepts any version it has a known schema
      for; newer payloads fall through to ``INTERNAL_ERROR``.
    """

    model_config = ConfigDict(extra="forbid")

    code: ErrorCode = Field(
        description=(
            "Machine-readable error identifier. ``RyotenkAIError.code`` "
            "for typed failures, ``INTERNAL_ERROR`` for unhandled "
            "``Exception``."
        ),
    )
    message: str = Field(
        description="Short, single-line human-readable summary. Never contains a traceback.",
    )
    traceback_summary: str | None = Field(
        default=None,
        description=(
            "Sanitised traceback tail (paths stripped, capped at 30 "
            "lines). ``None`` when no traceback is available."
        ),
    )
    exit_code: int = Field(
        description="POSIX exit code the trainer process exited with.",
    )
    wall_seconds: float = Field(
        ge=0.0,
        description="Wall-clock seconds from trainer start to handler firing.",
    )
    schema_version: int = Field(
        default=TRAINER_EXIT_SCHEMA_VERSION,
        ge=1,
        description="Payload schema version. Bumped on breaking field changes.",
    )

    def write_to(self, path: Path) -> None:
        """Atomically write the payload to ``path``.

        Uses the tmp + ``os.replace`` pattern so the supervisor never
        sees a partial file. Any IOError propagates — the trainer's
        atexit handler is expected to ``contextlib.suppress`` so a
        broken disk doesn't crash the exit path harder than the
        original failure.
        """
        import os
        import tempfile

        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a sibling tempfile in the same directory so
        # ``os.replace`` is atomic (cross-device renames are not).
        # NamedTemporaryFile with delete=False so we control the
        # rename ordering ourselves.
        fd, tmp_name = tempfile.mkstemp(
            prefix=".trainer-exit.",
            suffix=".json.tmp",
            dir=str(path.parent),
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(self.model_dump_json())
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp_name, path)
        except BaseException:
            # Cleanup tmp on any failure so the workdir doesn't
            # accumulate orphans. Suppression is fine — we re-raise.
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise

    @classmethod
    def read_from(cls, path: Path) -> "TrainerExitPayload | None":
        """Read + validate the payload from disk.

        Returns ``None`` when the file is absent (the common-case
        success path). Raises :class:`pydantic.ValidationError` on
        malformed JSON or unexpected keys — the supervisor catches
        this and falls back to the exit-code heuristic.
        """
        path = Path(path)
        if not path.exists():
            return None
        raw = path.read_text(encoding="utf-8")
        return cls.model_validate_json(raw)
